name: tests

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: neuroinformatics-unit/actions/lint@v2

  test:
    needs: [linting]
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ ubuntu-latest] # , windows-latest, macos-14, macos-13]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install viewephys from repo
        run: |
          python -m pip install --upgrade pip
          pip install .[qt]

      - name: Run tests
        run: |
          pytest

#  build_sdist_wheels:
#    name: Build source distribution
#    needs: [test]
#    if: github.event_name == 'push' && github.ref_type == 'tag'
#    runs-on: ubuntu-latest
#    steps:
#    - uses: neuroinformatics-unit/actions/build_sdist_wheels@v2


#  upload_all:
#    name: Publish build distributions
#    needs: [build_sdist_wheels]
#    if: github.event_name == 'push' && github.ref_type == 'tag'
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/download-artifact@v4
#      with:
#        name: artifact
#        path: dist
#    - uses: pypa/gh-action-pypi-publish@release/v1
#      with:
#        user: __token__
#        password: ${{ secrets.TWINE_API_KEY }}
